### ISSUE TITLE
EE3 version

### ISSUE THREAD

**Issue by ryanbrookepayne** [tjdraper/chrono#1]
@tjdraper We are using this on the United Way site (which we are updating to EE3). I was thinking of updating it for EE3 and doing a pull request here. However, is there a way to get years and months in EE3 without this addon?

**Comment by tjdraper** [comment]
I don't know of anything in EE 3 that does exactly what Chrono does directly. There are probably ways to get it done, but Chrono is fast and convenient. I clearly haven't had a need for it since whatever site I built it for at Caddis, but a pull request for an EE 3 version is welcome.
